### ISSUE TITLE
Adding vooplayer

### ISSUE THREAD

**Issue by fernandoch777** [dereuromark/media-embed#35]
Hello, can you add support for vooplayer?

This is an example URL: https://lds.cdn.vooplayer.com/publish/MTEwNTMw

Thanks

**Comment by dereuromark** [comment]
Can you make a PR for the stubs and add a test case?
Thank you.

**Comment by fernandoch777** [comment]
Sorry but I don't know how to do that...

**Comment by dereuromark** [comment]
You just add one here and see if it works:
https://github.com/dereuromark/MediaEmbed/blob/master/src/Data/stubs.php
You can make this as fork and then make a Pull Request to this repo.

**Comment by fernandoch777** [comment]
I am not a dev, I have no idea how to do that.

**Comment by dereuromark** [comment]
Oh i see. How did you get this lib installed and in use? Maybe that dev can help out.
Otherwise I will try to see into it in the next weeks.

**Comment by fernandoch777** [comment]
I am using phpBB which uses this library in an extension

https://www.phpbb.com/customise/db/extension/mediaembed/

**Comment by dereuromark** [comment]
Are you sure?
looking at https://github.com/s9e/TextFormatter/blob/master/src/Plugins/MediaEmbed/Parser.php this is its own thing, and unrelated to my library (even though I am using it for my own cakephp forum solutions so far).

**Comment by fernandoch777** [comment]
Please check the FAQ

https://www.phpbb.com/customise/db/extension/mediaembed/faq/2421

**Comment by fernandoch777** [comment]
The functionality is handled entirely by the 3rd-party library, known as MediaEmbed, bundled within phpBB.

But not sure...

**Comment by dereuromark** [comment]
They just happen to use the same name :)

**Comment by fernandoch777** [comment]
So not using this library? These are not the sites you support?

https://www.phpbb.com/customise/db/download/136051

**Comment by dereuromark** [comment]
I tried

	[
		'name' => 'Vooplayer',
		'website' => 'https://vooplayer.com/',
		'url-match' => 'https:\/\/lds\.cdn\.vooplayer\.com/publish/([0-9A-Za-z-]+)',
		'iframe-player' => 'https://lds.cdn.vooplayer.com/publish/$2',
		'embed-src' => '',
		'embed-width' => '480',
		'embed-height' => '270',
	],

Doesnt seem to like being iframed...

**Comment by petarsubotic** [comment]
@dereuromark you got two options

1. Simply append ?fallback=true to the source of the iframe
2. Alternatively, include the supporting script 
`<script src="https://app.vooplayer.com/assets/vooplayer.js"></script>`

furthermore, for the best matching you should try and avoid user subdomains
*.cdn.vopplayer.com could map to anything.cdn.vooplayer.com

**Comment by dereuromark** [comment]
@petarsubotic That actually worked, thx: https://github.com/dereuromark/media-embed/commit/f6fef9fba134819bc2428c58f98b6f568d37c85d
