### ISSUE TITLE
Handle strings with multiple links?

### ISSUE THREAD

**Issue by kylescousin** [dereuromark/media-embed#36]
What is the best way to give MediaEmbed a full string in which it finds all embeddable links?

**Comment by dereuromark** [comment]
You need to parse them yourself similar to how bbcode examples work.

**Comment by dereuromark** [comment]
If you can, you can also PR a solution to extract those as high level wrapper/method etc.

**Comment by derUli** [comment]
Is the text containg the urls plaintext, html or markdown / bbcode?

I wrote a class which replaces a-tags in html with media embeds.

**Comment by dereuromark** [comment]
I think as per use case those can all be relevant.
Ideally you have a class for each of those that you need per context.

We could add examples into the docs here for each one.
