### ISSUE TITLE
Please provide an alternative to composer

### ISSUE THREAD

**Issue by r3wt** [dereuromark/media-embed#4]
please provide alternative or atleast some instructions for autoloading this into a project w/o composer.

**Comment by pault83** [comment]
Hello, sorry to drag this up again, but I have a similar issue. I can't install Composer (no shell access to my hosting) so I've been trying to include all the MediaEmbed files manually. I get parse errors on lines like protected $_hosts = []; I can't think what I'm doing wrong?

**Comment by dereuromark** [comment]
Can you paste the exact issue?

**Comment by pault83** [comment]
I do: 
require_once('MediaEmbed/MediaEmbed.php'); 
require_once('MediaEmbed/Data/stubs.php'); 
require_once('MediaEmbed/Object/MediaObject.php');
require_once('MediaEmbed/Object/ObjectInterface.php');

and immediately get: 
Parse error: syntax error, unexpected '[' in /home/ [snip] /MediaEmbed/MediaEmbed.php on line 22

**Comment by dereuromark** [comment]
Sure you are using php5.4+ AS documented?

**Comment by pault83** [comment]
Sorry, my bad, 5.3.29. Presumed the host was uptodate. Thanks.

**Comment by pault83** [comment]
Sorry, my mistake. I upgraded it to 5.4.45 now but get a new error: 

Fatal error: Interface 'MediaEmbed\Object\ObjectInterface' not found in /home/ [snip] /MediaEmbed/Object/MediaObject.php on line 12

**Comment by dereuromark** [comment]
I bet that has to do wih not using namespaces and/or composer.

**Comment by pault83** [comment]
So definitely no way to use it without composer? And no way to install composer without shell access...

**Comment by dereuromark** [comment]
Read about that on in the internet.
I bet you can dev locally and just copy-and-paste/ftp-load the whole code including autoloader map to the live system in that case.
But that has nothing to do with his bug tracker.

**Comment by pault83** [comment]
Okay thanks for your help.
