### ISSUE TITLE
Add Soundcloud Support

### ISSUE THREAD

**Issue by derUli** [dereuromark/media-embed#43]
It would be nice to have support for embedding soundcloud players.
It's a popular audio streaming platform used by musicians, labels and podcasts.

**Comment by dereuromark** [comment]
Anyone able to make a PR for it?

**Comment by derUli** [comment]
I can take a look at this.
I have vacation days for the next two weeks.

It looks like soundcloud supports oEmbed.
I think it makes sense to implement support for generic oEmbed resources instead of implementing a soundcloud specific solution.
We could use an oembed php library and try to use oEmbed for all unknown services.

@dereuromark what do you think?

**Comment by dereuromark** [comment]
I am fine either way.
We could for now add basic support for soundcloud the current way and start a new branch with improved feature support as generic solution on top?

**Comment by derUli** [comment]
I took a look into your current implementation in my lunchbreak.
So you just extract the Id from the input url by regex, then insert the id into another url and build an iframe?
Then this is very easy to implement.

**Comment by derUli** [comment]
Created a pull request

https://github.com/dereuromark/media-embed/pull/44/commits

**Comment by dereuromark** [comment]
Awesome, thank you!
As for the generic rewrite, any maybe using value objects and more, we should have a separate discussion, and create a new develop branch for a new major release then.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/media-embed/issues/45
