### ISSUE TITLE
Version 0.5.2 still not available by composer

### ISSUE THREAD

**Issue by derUli** [dereuromark/media-embed#47]
The version 0.5.2 is still not available at packagist.
https://packagist.org/packages/dereuromark/media-embed

**Comment by dereuromark** [comment]
Weird. Ok now?

**Comment by derUli** [comment]
yes. Works now. Including my soundcloud support. 😎

**Comment by dereuromark** [comment]
I wonder if the repo rename had some issues with packagist auto update
