### ISSUE TITLE
what local formats are avalible

### ISSUE THREAD

**Issue by regchanuk** [dereuromark/media-embed#51]
what local files can be played MP4 MP3 AVI etc what formats please can you tell us thanks

**Comment by derUli** [comment]
There are no local formats.
This framework is only for embedding content from streaming services such as Youtube.

**Comment by derUli** [comment]
If you search a player for local video or audio files which looks better than the native HTML5 <audio> or <video> then take a look at MediaElement.js
https://www.mediaelementjs.com/
