### ISSUE TITLE
Soundcloud urls not working

### ISSUE THREAD

**Issue by wpas81** [dereuromark/media-embed#54]
Hi

soundcloud url's are currently not working (they do in the sandbox).  

(+ superb package!)

**Comment by dereuromark** [comment]
Is there any fix you could recommend?

**Comment by wpas81** [comment]
I got it... I've included joe1992w/laravel-media-embed in my Laravel project which uses your package. But I think it's an older version that's included? If I compare the stubs-file in my project with the current one here on github it's missing a lot of parameters. So I've copy/pasted the soundcloud-array and it's good now. (I'm not very familiar with Github, so I'm not sure what the best approach would be)
Thanks for responding. Did not expect that.

**Comment by derUli** [comment]
I contributed the Soundcloud support some time ago.
I tested it with the current version of the media-embed package and it still works.
So you could fork the laravel wrapper and increase the version of media-embed.

**Comment by wpas81** [comment]
Thanks I'll do that. I did find one other issue. I tried adding a youtube-playlist via an url like this:
https://www.youtube.com/embed/JQz_WjTn68U?playlist=bYexhc0MqQQ,YZzmQVbwAgQ,FSFMyeGwXIw,t25q92grpbc,uCenCFOcrtI,VXB30PW7aVY,Z6yavVzfs58,uqrO2y6L0z0,uwCInRJVhwQ,&loop=1
But your class only takes the 1st video and ignores the others. The regex should match them all
