### ISSUE TITLE
PHP 8.2: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by lubos-h** [dereuromark/media-embed#62]
Good day, I would like to report error on:

/src/Object/MediaObject.php: line 662
`protected function _esc($text) {
		return htmlspecialchars($text, ENT_QUOTES, '', false);
	}`

When passing NULL value as $text, this triggers error in **PHP 8.2**:
`htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated`

This happens when NULL value is passed by code on line 624 (flashvars):
`$flashvars = $this->_esc($flashvars)`

**Comment by dereuromark** [comment]
Would you mind making a PR?

**Comment by dereuromark** [comment]
Should be resolved with https://github.com/dereuromark/media-embed/releases/tag/0.5.9

**Comment by lubos-h** [comment]
Hi @dereuromark , just tested, works like charm. Thank you!

**Comment by dereuromark** [comment]
Could you also try master maybe? A new release with types and 8.1+ is coming out soon

**Comment by lubos-h** [comment]
> Could you also try master maybe? A new release with types and 8.1+ is coming out soon

Sorry, I should mention, yes, tried the master and all worked.
